### ISSUE TITLE
Build Error due to Missing Icon: Request for Addition

### ISSUE THREAD

**Issue by mentoster** [leedave/flipper-zero-fap-boilerplate#18]
# Build Error due to Missing Icon: Request for Addition

I encountered a build error in the `boilerplate_scene_scene_4_on_enter` file due to a missing icon reference. The specific line of code is as follows:

```c
dialog_file_browser_set_basic_options(&browser_options, SUBGHZ_APP_EXTENSION, &I_sub1_10px);
```

It appears the icon `I_sub1_10px` is not available in the icons folder. This omission is causing a build error, and I am unable to proceed without this icon.

Could you please add the `I_sub1_10px` icon to the icons folder? 

### To fix right now:
1. Delete this stroke in **boilerplate.h**
```c
#include <assets_icons.h>
```  
2. Delete this stroke
```c
dialog_file_browser_set_basic_options(&browser_options, SUBGHZ_APP_EXTENSION, &I_sub1_10px);
```

**Comment by leedave** [comment]
Thank you for the notice. 

I've added the icon and made sure the application is compatible to non-fbt compilations such as with ufbt.
