### ISSUE TITLE
boilerplate_icons.h does not exist

### ISSUE THREAD

**Issue by vguttmann** [leedave/flipper-zero-fap-boilerplate#21]
I'm using this as the start for another app, and found that boilerplate_icons.h doesn't seem to exist

**Comment by vguttmann** [comment]
I'm an idiot and didn't realize that ufbt created that file...

**Comment by leedave** [comment]
Most flipper users don't even get to the point where they try to make an app. So you're definitely smarter than them 😉.

**Comment by vguttmann** [comment]
Well, currently no CAN FD sniffer exists, so if I want one, I gotta make it myself, ain't I?
