### ISSUE TITLE
Missing `furi_string_free`

### ISSUE THREAD

**Issue by derskythe** [leedave/flipper-zero-fap-boilerplate#23]
Hi, found missing `furi_string_free` when `flipper_format_file_open_existing` or `flipper_format_read_header` is failed. 

https://github.com/leedave/flipper-zero-fap-boilerplate/blob/2fb827d8abab9b0b84023172407756d791f3721e/helpers/boilerplate_storage.c#L83

https://github.com/leedave/flipper-zero-fap-boilerplate/blob/2fb827d8abab9b0b84023172407756d791f3721e/helpers/boilerplate_storage.c#L85

https://github.com/leedave/flipper-zero-fap-boilerplate/blob/2fb827d8abab9b0b84023172407756d791f3721e/helpers/boilerplate_storage.c#L92

https://github.com/leedave/flipper-zero-fap-boilerplate/blob/2fb827d8abab9b0b84023172407756d791f3721e/helpers/boilerplate_storage.c#L99

**Comment by leedave** [comment]
Thank you for your contribution. 

- Code fixed
- Added you to contribution credits
